language: node_js
node_js:
  - 0.12
branches:
  only:
    - active
    - test
install:
  - npm install
  - npm i -g batshit
before_script:
  - ./cli.js -rt &
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
